baseurl = "https://ertianchen.github.io/"
relativeURLs = false  # Change to false
title = "Ertian Chen (陈尔天)"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Assistant Professor of Economics <br> Xiamen University <br> Email: <a href='mailto:ertianchen@gmail.com'>ertianchen@gmail.com</a>"
    logo = "Ertian_Chen.jpeg"
