baseurl = "https://ertianchen.github.io/"
relativeURLs = false  # Change to false
title = "Ertian Chen (陈尔天)"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Ph.D. candidate in Economics <br> University College London <br> Email: <a href='mailto:ertian.chen.19@ucl.ac.uk'>ertian.chen.19@ucl.ac.uk</a>"
    logo = "Ertian_Chen.jpeg"
